import { createClient, type PaperboyClient } from "@paperboycms/client";
import { constantTimeEqual, verifyPreviewToken } from "@paperboycms/client/preview-token";

/**
 * The one place this app talks to Paperboy.
 *
 * Two rules worth keeping if you rewrite it:
 *
 *  1. The PREVIEW key is server-side only. It returns unpublished drafts, so it
 *     must never reach a browser bundle — read it here, in server code, and pass
 *     rendered output to the client. (Astro renders `.astro` on the server, so
 *     importing this from a page is safe; importing it from a `<script>` is not.)
 *  2. Which key you use IS the security boundary. `isPreview()` decides, and it
 *     fails closed.
 */

/**
 * Env, read from wherever this is deployed. `Astro.locals.runtime.env` is where
 * Cloudflare puts bindings; Node and the dev server use `process.env` /
 * `import.meta.env`. Checking all three means the same code deploys anywhere.
 */
export type Env = Record<string, string | undefined> | undefined;

export function readEnv(env: Env, key: string): string | undefined {
  if (env && env[key]) return env[key];
  const proc = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process;
  if (proc?.env?.[key]) return proc.env[key];
  return (import.meta as unknown as { env?: Record<string, string | undefined> }).env?.[key];
}

export interface CmsConfig {
  apiUrl: string;
  publicKey: string;
  previewKey: string;
  previewSecret: string;
  /**
   * Which language to serve. Empty means "whatever the API's default is".
   *
   * Content in Paperboy is localized, and a page's urlPath is per LOCALE — so a
   * Norwegian site whose front page lives at /hjem gets a 404 from an English
   * request. One route can only serve one locale; set this to pick which. For a
   * genuinely multilingual site, add a [locale] segment to the route and pass it
   * through instead (apps/web in the Paperboy repo does that).
   */
  locale: string;
}

export function config(env: Env): CmsConfig {
  return {
    apiUrl: (readEnv(env, "PAPERBOY_API_URL") ?? "").replace(/\/+$/, ""),
    publicKey: readEnv(env, "PAPERBOY_PUBLIC_KEY") ?? "",
    previewKey: readEnv(env, "PAPERBOY_PREVIEW_KEY") ?? "",
    previewSecret: readEnv(env, "PREVIEW_SECRET") ?? "",
    locale: readEnv(env, "PAPERBOY_LOCALE") ?? "",
  };
}

// Memoized per (url, key) rather than a module-level singleton: on a serverless
// runtime the env arrives per request, and preview vs public are different keys.
const clients = new Map<string, PaperboyClient>();

export function cms(env: Env, preview = false): PaperboyClient {
  const c = config(env);
  const key = preview ? c.previewKey : c.publicKey;
  const cacheKey = `${c.apiUrl}|${key}`;
  let client = clients.get(cacheKey);
  if (!client) {
    client = createClient({ baseUrl: c.apiUrl, key });
    clients.set(cacheKey, client);
  }
  return client;
}

/**
 * Does this request carry a valid preview credential?
 *
 * Two accepted forms:
 *   ?pbt=<token>  a short-lived token the admin minted and signed. This is what
 *                 the preview iframe sends; the browser never holds the secret.
 *   ?pb=<secret>  the raw secret, for server-side or CLI callers that hold it.
 *
 * The verification comes from `@paperboycms/client/preview-token` — a SEPARATE
 * subpath from the client itself, because its first argument is your
 * PREVIEW_SECRET and nothing that reaches a browser bundle may hold that. Do not
 * reimplement it: comparing a MAC by hand is how drafts end up on public sites.
 *
 * Async because that verification is WebCrypto, which is what lets this same file
 * run on Node, Cloudflare Workers, Deno and Bun.
 */
export async function isPreview(url: URL, env?: Env): Promise<boolean> {
  const { previewSecret } = config(env);
  if (!previewSecret) return false;

  const pb = url.searchParams.get("pb");
  if (pb !== null && constantTimeEqual(pb, previewSecret)) return true;
  return verifyPreviewToken(previewSecret, url.searchParams.get("pbt"));
}

/**
 * Preview has to survive navigation INSIDE the preview iframe, or clicking a
 * link in the admin's preview pane silently drops you onto the published site.
 * Carry the credential on internal links while previewing.
 */
export function withPreview(href: string, url: URL): string {
  const pbt = url.searchParams.get("pbt");
  const pb = url.searchParams.get("pb");
  if (!pbt && !pb) return href;
  if (!href.startsWith("/")) return href;
  const next = new URL(href, url.origin);
  if (pbt) next.searchParams.set("pbt", pbt);
  else if (pb) next.searchParams.set("pb", pb);
  return `${next.pathname}${next.search}`;
}

/**
 * robots.txt, sitemap.xml, llms.txt and security.txt are GENERATED by Paperboy
 * from your content and site settings, then proxied from this origin — so they
 * are never stale after a publish, and editors change them without a deploy.
 * Configure them in the admin under Settings → Site → Public files.
 */
export async function fetchPublicFile(
  env: Env,
  name: "robots.txt" | "sitemap.xml" | "llms.txt" | "security.txt",
): Promise<{ body: string; contentType: string } | null> {
  const c = config(env);
  if (!c.apiUrl || !c.publicKey) return null;
  try {
    const res = await fetch(`${c.apiUrl}/api/v1/delivery/${name}`, {
      headers: { authorization: `Bearer ${c.publicKey}` },
    });
    if (!res.ok) return null;
    return {
      body: await res.text(),
      contentType: res.headers.get("content-type") ?? "text/plain; charset=utf-8",
    };
  } catch {
    // A CMS hiccup must never break crawling — callers fall back.
    return null;
  }
}

/** One published page, as the delivery inventory reports it. */
export interface PageInventoryEntry {
  documentId: string;
  type: string;
  name: string;
  locale: string;
  urlPath: string;
  lastmod?: string;
  noIndex?: boolean;
}

/**
 * Every published page, for building robots/sitemap/llms.txt OURSELVES.
 *
 * Why not just proxy the CMS's generated files: they compose absolute URLs as
 * `{canonicalBaseUrl}/{locale}{urlPath}`, which is the reference frontend's
 * scheme. This app serves pages WITHOUT a locale segment, so every proxied URL
 * was an alias — a sitemap full of URLs that are not the canonical ones, which
 * is worse than no sitemap. CLAUDE.md sanctions exactly this: other frontends
 * build from /delivery/pages.
 */
export async function fetchPageInventory(env: Env): Promise<PageInventoryEntry[]> {
  const c = config(env);
  if (!c.apiUrl || !c.publicKey) return [];
  try {
    const res = await fetch(`${c.apiUrl}/api/v1/delivery/pages`, {
      headers: { authorization: `Bearer ${c.publicKey}` },
    });
    if (!res.ok) return [];
    const body = (await res.json()) as { pages?: PageInventoryEntry[] };
    return Array.isArray(body.pages) ? body.pages : [];
  } catch {
    // A CMS hiccup must never break crawling — callers fall back.
    return [];
  }
}

/** The start page's documentId, so it can be emitted as "/" rather than its slug. */
export async function fetchStartPageId(env: Env): Promise<string | null> {
  try {
    const start = await cms(env).startPage({ populate: 0 });
    return start?.documentId ?? null;
  } catch {
    return null;
  }
}
