import type { APIContext } from "astro";
import { fetchPublicFile } from "../../lib/cms";

// security.txt (RFC 9116) at its well-known path. Generated by Paperboy, whose
// `Expires` is a rolling window computed per request — so it cannot go stale the
// way a hand-committed file does.
export const prerender = false;

export async function GET(context: APIContext): Promise<Response> {
  const env = (context.locals as { runtime?: { env?: Record<string, string | undefined> } }).runtime?.env;
  const file = await fetchPublicFile(env, "security.txt");
  if (!file) return new Response("Not found", { status: 404 });
  return new Response(file.body, {
    headers: {
      "Content-Type": file.contentType,
      "Cache-Control": "public, max-age=300, stale-while-revalidate=600",
    },
  });
}
