import type { APIContext } from "astro";
import { fetchPublicFile } from "../lib/cms";

// Generated by Paperboy from your content and site settings, proxied from this
// origin so it is never stale after a publish and editors change it without a
// deploy. Configure it under Settings → Site → Public files.
export const prerender = false;

// A CMS hiccup must never break crawling, so fall back to allow-all rather than
// to nothing (an empty or 500 robots.txt is treated as "crawl everything" by
// some bots and "crawl nothing" by others — say it explicitly).
const FALLBACK = ["User-agent: *", "Allow: /", ""].join("\n");

export async function GET(context: APIContext): Promise<Response> {
  const env = (context.locals as { runtime?: { env?: Record<string, string | undefined> } }).runtime?.env;
  const file = await fetchPublicFile(env, "robots.txt");
  return new Response(file?.body ?? FALLBACK, {
    headers: {
      "Content-Type": file?.contentType ?? "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=300, stale-while-revalidate=600",
    },
  });
}
