import type { APIContext } from "astro";
import { fetchPublicFile } from "../lib/cms";

// Generated by Paperboy from the pages it can see: noIndex pages are excluded,
// so the sitemap never advertises a path an editor opted out of. Proxied from
// this origin so it is never stale after a publish.
export const prerender = false;

// An empty but VALID urlset beats a 500: a malformed sitemap can get a site's
// whole submission rejected.
const FALLBACK =
  '<?xml version="1.0" encoding="UTF-8"?>' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>';

export async function GET(context: APIContext): Promise<Response> {
  const env = (context.locals as { runtime?: { env?: Record<string, string | undefined> } }).runtime?.env;
  const file = await fetchPublicFile(env, "sitemap.xml");
  return new Response(file?.body ?? FALLBACK, {
    headers: {
      "Content-Type": file?.contentType ?? "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=300, stale-while-revalidate=600",
    },
  });
}
